FORMAT: 1A
HOST: https://api.agrofoto.pl

# Agrofoto
Agrofoto REST API

## Request info
Collection always consists of:

 - `href`that uniquely identifies the collection, 
 - `items table that contains all or some of the actual resources,
 - `previous and `next` which allow for paging

### Access token
Access token should be obtained after logging in.
Every request will contain an access_token parameter eg. https://api.agrofoto.pl/galleries?access_token=CAACEdEose0c
If annonymous (without logging in) application access should be possible - no access token in request present case support is needed and treated as a request from unauthenticated user.


# Agrofoto API Root [/]
API Root

References other api resources, field expansion allows to fetch content with single request


Attributes of the root resource:

 - `gallery` is a root gallery resource
 - `forum` is a root forum resource

## Retrieve Entry Point [GET]

+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/",
                "galleries": {
                    "href": "https://api.agrofoto.pl/galleries"
                },
                "forums": {
                    "href": "https://api.agrofoto.pl/forums"
                }
            }

# Group Authentication
Seesion management

## Login [/login]
If some other session parameters are neccessary prior to actual login request, they could be obtained with GET request on login endpoint. Please report this issue if necessary.

### Login [POST]
Performs the login.

+ Request (application/x-www-form-urlencoded)

        login=test&password=qq
            
+ Response 204
    + Headers
    
            Set-Cookie: token=xxx; path=/; expires=Fri, 03-May-2013 03:01:54 GMT; secure; HttpOnly

### Logout [DELETE]
Performs logout.
+ Response 204

# Group Galleries
Gallery releated resources

## Gallery [/galleries/{id}]
A single Gallery object. Gallery object represents a node in the tree of galleries.

Following gallery object types should be considered:

- root - hot photos, children, no parent, no photos
- node - hot photos, children, parent, no photos
- leaf - hot photos, no children, parent, photos
- leaf-vip - leaf with from and rating

+ Parameters
    + id (string)

### Get the Gallery [GET]
+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/galleries/29-case",
                "title": "Case",
                "desc": null,
                "updatedTime": "2014-04-14T02:15:15Z",
                "photosCount": 3724,
                "commentsCount": 15286,
                "cover": {
                    "href": "http://www.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86",
                    "user": {
                        "href": "https://api.agrofoto.pl/users/14237-mat",
                        "name": "Mat"
                    },
                    "name": "Case 115 i Claas Dominator 86",
                    "desc": "1-szy dzień żniw.",
                    "images": {
                        "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/tn_gallery_14237_29_53604.jpg",
                        "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/sml_gallery_14237_29_53604.jpg",
                        "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/med_gallery_14237_29_53604.jpg",
                        "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/gallery_14237_29_53604.jpg"
                    },
                    "createdTime": "2011-09-02T15:41:47+0000",
                    "updatedTime": "2011-09-02T16:12:33+0000",
                    "displayedCount": 91,
                    "commentsCount": 1
                },
                "subscribe": {
                    "href": "https://api.agrofoto.pl/galleries/29-case/subscribe",
                    "count": 3,
                    "subscribed": true
                },
                "share": "http://www.agrofoto.pl/forum/gallery/category/29-case/",
                "canUpload": true,
                "parent": {
                    "href": "https://api.agrofoto.pl/galleries/4-ciagniki-tractors",
                    "title": "Ciągniki / Tractors",
                    "parent": {
                        "href": "https://api.agrofoto.pl/galleries/2-maszyny-machines",
                        "title": "Maszyny / Machines",
                        "parent": {
                            "href": "https://api.agrofoto.pl/galleries",
                            "title": "Galerie",
                            "parent": null
                        }
                    }
                },
                "children": {
                    "href": "https://api.agrofoto.pl/galleries/{id}/children",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/galleries/224-challenger",
                            "title": "Challenger",
                            "desc": null,
                            "updatedTime": "2014-04-14T02:15:15Z",
                            "photosCount": 83,
                            "commentsCount": 394,
                            "cover": {
                                "href": "http://www.agrofoto.pl/photos/504435-challenger-mt-765c",
                                "user": {
                                    "href": "https://api.agrofoto.pl/users/1342-mnich",
                                    "name": "mnich"
                                },
                                "name": "Challenger MT 765C",
                                "desc": "Siew kukurydzy siewnikiem horsch.",
                                "images": {
                                    "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/tn_gallery_1342_224_40598.jpg",
                                    "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/sml_gallery_1342_224_40598.jpg",
                                    "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/med_gallery_1342_224_40598.jpg",
                                    "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/gallery_1342_224_40598.jpg"
                                },
                                "createdTime": "2011-09-02T15:41:47+0000",
                                "updatedTime": "2011-09-02T16:12:33+0000",
                                "displayedCount": 433,
                                "commentsCount": 4
                            }
                        }
                    ],
                    "next": {
                        "href": "https://api.agrofoto.pl/galleries/29-case/children?page=1&limit=25"
                    },
                    "previous": null
                },
                "photos": {
                    "href": "https://api.agrofoto.pl/galleries/29-case/photos",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86",
                            "user": {
                                "href": "https://api.agrofoto.pl/users/14237-mat",
                                "name": "Mat"
                            },
                            "name": "Case 115 i Claas Dominator 86",
                            "desc": "1-szy dzień żniw.",
                            "images": {
                                "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/tn_gallery_14237_29_53604.jpg",
                                "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/sml_gallery_14237_29_53604.jpg",
                                "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/med_gallery_14237_29_53604.jpg",
                                "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/gallery_14237_29_53604.jpg"
                            },
                            "createdTime": "2011-09-02T15:41:47+0000",
                            "updatedTime": "2011-09-02T16:12:33+0000",
                            "displayedCount": 91,
                            "commentsCount": 1
                        }
                    ],
                    "next": { 
                        "href": "https://api.agrofoto.pl/galleries/29-case/photos?page=1&limit=25" 
                    },
                    "previous": null
                },
                "hot": {
                    "href": "https://api.agrofoto.pl/galleries/29-case/hot",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86",
                            "user": {
                                "href": "https://api.agrofoto.pl/users/14237-mat",
                                "name": "Mat"
                            },
                            "name": "Case 115 i Claas Dominator 86",
                            "desc": "1-szy dzień żniw.",
                            "images": {
                                "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/tn_gallery_14237_29_53604.jpg",
                                "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/sml_gallery_14237_29_53604.jpg",
                                "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/med_gallery_14237_29_53604.jpg",
                                "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/gallery_14237_29_53604.jpg"
                            },
                            "createdTime": "2011-09-02T15:41:47+0000",
                            "updatedTime": "2011-09-02T16:12:33+0000",
                            "displayedCount": 91,
                            "commentsCount": 1
                        }
                    ],
                    "next": {
                        "href": "https://api.agrofoto.pl/galleries/29-case/hot?page=1&limit=25"
                    },
                    "previous": null
                },
                "rate": {
                    "href": "https://api.agrofoto.pl/galleries/29-case/rate",
                    "rating": 5,
                    "count": 2,
                    "userRating": 5
                },
                "from": {
                    "href": "https://api.agrofoto.pl/users/14237-mat",
                    "name": "Mat"
                }
            }

## Gallery subscribing [/galleries/{id}/subscribe]

+ Parameters
    + id (string)

+ Model
    + Body
    
            {
                "href": "https://api.agrofoto.pl/galleries/29-case/subscribe",
                "count": 3,
                "subscribed": true
            }

### Subscribe the gallery [PUT]
+ Response 200 (application/json)

    [Gallery subscribing][]    

### Unsubscribe the gallery [DELETE]
+ Response 200 

    [Gallery subscribing][]

## Gallery rating [/galleries/{id}/rate]
Rate the gallery

+ Parameters
    + id (string)

+ Model (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/galleries/29-case/rate",
                "rating": 5,
                "count": 2,
                "userRating": 5
            }

### Get gallery rating [GET]
+ Response 200 (application/json)

    [Gallery rating][]

### Rate the gallery [PUT]
Rate or update user vote

+ Request (application/json)

            {
                "rating": 5.0
            }
            
+ Response 200 (application/json)

    [Gallery rating][]

## Gallery children [/galleries/{id}/children]
Subgalleries of given gallery node, also user albums

+ Parameters
    + id (string)
    
### List gallery children [GET]
+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/galleries/{id}/children",
                "items": [
                    {
                        "href": "https://api.agrofoto.pl/galleries/224-challenger",
                        "title": "Challenger",
                        "desc": null,
                        "updatedTime": "2014-04-14T02:15:15Z",
                        "photosCount": 83,
                        "commentsCount": 394,
                        "cover": {
                            "href": "http://www.agrofoto.pl/photos/504435-challenger-mt-765c",
                            "user": {
                                "href": "https://api.agrofoto.pl/users/1342-mnich",
                                "name": "mnich"
                            },
                            "name": "Challenger MT 765C",
                            "desc": "Siew kukurydzy siewnikiem horsch.",
                            "images": {
                                "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/tn_gallery_1342_224_40598.jpg",
                                "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/sml_gallery_1342_224_40598.jpg",
                                "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/med_gallery_1342_224_40598.jpg",
                                "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_224/gallery_1342_224_40598.jpg"
                            },
                            "createdTime": "2011-09-02T15:41:47+0000",
                            "updatedTime": "2011-09-02T16:12:33+0000",
                            "displayedCount": 433,
                            "commentsCount": 4
                        }
                    }
                ],
                "next": {
                    "href": "https://api.agrofoto.pl/galleries/29-case/children?page=1&limit=25"
                },
                "previous": null
            }


# Group Photos
    
## Photos Collection [/galleries/{id}/photos]
Photos collection for given gallery leaf
    
### List all Photos [GET]
+ Parameters
    + id (string)
    
+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/galleries/29-case/photos",   
                "items": [ 
                    {
                        "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86",
                        "user": {
                            "href": "https://api.agrofoto.pl/users/14237-mat",
                            "name": "Mat"
                        },
                        "name": "Case 115 i Claas Dominator 86",
                        "desc": "1-szy dzień żniw.",
                        "images": {
                            "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/tn_gallery_14237_29_53604.jpg",
                            "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/sml_gallery_14237_29_53604.jpg",
                            "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/med_gallery_14237_29_53604.jpg",
                            "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/gallery_14237_29_53604.jpg"
                        },
                        "createdTime": "2011-09-02T15:41:47+0000",
                        "updatedTime": "2011-09-02T16:12:33+0000", 
                        "displayedCount": 91,
                        "commentsCount": 1
                    }
                ],
                "next": { 
                    "href": "https://api.agrofoto.pl/galleries/29-case/photos?page=1&limit=25" 
                },
                "previous": null
            }

### Photo upload [POST]
Photo upload is a multipart entity, not sure how to model that...

+ Request (applicatoin/json)

            {
                "name": "Case 115 i Claas Dominator 86",
                "desc": "1-szy dzień żniw."
            }

+ Response 201 (application/json)
    + Body
            
            {
                "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86"
            }

## Hot photos collection [/galleries/{id}/hot]
Hot photos collection for given gallery root/node/leaf
    
### List all hot photos [GET]
+ Parameters
    + id (string)
    
+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/galleries/29-case/hot",
                "items": [
                    {
                        "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86",
                        "user": {
                            "href": "https://api.agrofoto.pl/users/14237-mat",
                            "name": "Mat"
                        },
                        "name": "Case 115 i Claas Dominator 86",
                        "desc": "1-szy dzień żniw.",
                        "images": {
                            "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/tn_gallery_14237_29_53604.jpg",
                            "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/sml_gallery_14237_29_53604.jpg",
                            "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/med_gallery_14237_29_53604.jpg",
                            "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/gallery_14237_29_53604.jpg"
                        },
                        "createdTime": "2011-09-02T15:41:47+0000",
                        "updatedTime": "2011-09-02T16:12:33+0000",
                        "displayedCount": 91,
                        "commentsCount": 1
                    }
                ],
                "next": {
                    "href": "https://api.agrofoto.pl/galleries/29-case/hot?page=1&limit=25"
                },
                "previous": null
            }

## Photo [/photos/{id}]
Single photo resource

+ Parameters
    + id (string)

### Get the Photo [GET]
    
+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86",
                "gallery": {
                    "href": "https://api.agrofoto.pl/galleries/29-case",
                    "title": "Case"
                },
                "user": {
                    "href": "https://api.agrofoto.pl/users/14237-mat",
                    "name": "Mat",
                    "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-14237.jpg"
                },
                "name": "Case 115 i Claas Dominator 86",
                "desc": "1-szy dzień żniw.",
                "images": {
                    "square": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/tn_gallery_14237_29_53604.jpg",
                    "small": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/sml_gallery_14237_29_53604.jpg",
                    "medium": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/med_gallery_14237_29_53604.jpg",
                    "large": "http://www.agrofoto.pl/forum/uploads/gallery/category_29/gallery_14237_29_53604.jpg"
                },
                "createdTime": "2011-09-02T15:41:47+0000",
                "updatedTime": "2011-09-02T16:12:33+0000",
                "displayedCount": 91,
                "commentsCount": 1,
                "link": "http://www.agrofoto.pl/forum/gallery/image/514762-case-115-i-claas-dominator-86/",
                "rate": {
                    "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/rate",
                    "rating": 5,
                    "ratingCount": 2,
                    "userRating": 5
                },
                "subscribe": {
                    "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/subscribe",
                    "count": 4,
                    "subscribed": true
                },
                "comments": {
                    "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/comments",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/comments/1544809",
                            "user": {
                                "href": "https://api.agrofoto.pl/users/19727-michal15555",
                                "name": "michal15555",
                                "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-19727.jpg"
                            },
                            "message": "Jaki plon ?"
                        }
                    ],
                    "next": {
                        "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/comments?page=1&limit=25"
                    },
                    "previous": null
                }
            }

### Delete the photo [DELETE]
+ Response 204

## Photo rating [/photos/{id}/rate]
Rate the photo

+ Parameters
    + id (string)

+ Model (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/rate",
                "rating": 5.0,
                "ratingCount": 2,
                "userRating": 5.0
            }


### Get photo rating [GET]
+ Response 200 (application/json)

    [Photo rating][]

### Rate the photo [PUT]
Rate or update user vote

+ Request (application/json)

            {
                "rating": 5.0
            }
            
+ Response 200 (application/json)

    [Photo rating][]

## Photo subscribing [/photos/{id}/subscribe]

+ Parameters
    + id (string)

+ Model
    + Body
    
            {
                "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/subscribe",
                "count": 4,
                "subscribed": true
            }

### Subscribe the photo [PUT]
+ Response 200 (application/json)

    [Photo subscribing][]    

### Unsubscribe the photo [DELETE]
+ Response 200 

    [Photo subscribing][]

# Group Comments

## Comments collection [/photos/{id}/comments]

+ Parameters
    + id (string)

+ Model
    + Body
    
            {
                "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/comments",
                "items": [
                    {
                        "href": "https://api.agrofoto.pl/comments/1544809",
                        "user": {
                            "href": "https://api.agrofoto.pl/users/19727-michal15555",
                            "name": "michal15555",
                            "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-19727.jpg"
                        },
                        "message": "Jaki plon ?"
                    }
                ],
                "next": {
                    "href": "https://api.agrofoto.pl/photos/514762-case-115-i-claas-dominator-86/comments?page=1&limit=25"
                },
                "previous": null
            }  

### Get all comments [GET]
+ Response 200 (application/json)

    [Comments collection][]

### Post a comment [POST]
+ Request (application/json)

            {
                "message": "Jaki plon ?"
            }
            
+ Response 200 (application/json)

    [Comments collection][]
    
## Comment [/comments/{id}]

+ Parameters
    + id (string)

+ Model
    + Body
    
            {
                "href": "https://api.agrofoto.pl/comments/1544809",
                "user": {
                    "href": "https://api.agrofoto.pl/users/19727-michal15555",
                    "name": "michal15555",
                    "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-19727.jpg"
                },
                "message": "Jaki plon ?"
            }

### Get the comment [GET]
+ Response 200 (application/json)

    [Comment][]
    
### Update the comment [PUT]
+ Request (application/json)

            {
                "message": "Jaki plon ?"
            }
            
+ Response 200 (application/json)

    [Comments collection][]
    
### Delete the comment [DELETE]
+ Response 204

# Group Forums
Forum related resources

## Forum [/forums/{id}]
A single forum object. Forum object represents a node in the tree of forums.

Following forum object types should be considered:

- root - hot topics, children, no parent, no topics
- node - no hot topics, children, parent, topics/no topics
- leaf - no hot topics, no children, parent, topics

The following example api response is a hybrid of all three node types.

+ Parameters
    + id (string)

### Get Forum [GET]
+ Response 200 (application/json)
    + Body
    
            {
                "href": "https://api.agrofoto.pl/forums/178-jeczmien",
                "title": "Jęczmień",
                "icon": "http://www.agrofoto.pl/forum/uploads/forumicons/41-icon-2145d8666c5e8ca7b66e6f57d61b939b.jpg",
                "unread": true,
                "topic_count": 107,
                "posts_count": 4472,
                "latest_topic": {
                    "href": "https://api.agrofoto.pl/topics/54612-jeczmien-hybrydowy",
                    "title": "jęczmień hybrydowy",
                    "user": {
                        "href": "https://api.agrofoto.pl/users/69429-rapscase",
                        "name": "RAPSCASE",
                        "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-14237.jpg"
                    },
                    "updated_time": "2011-09-02T16:12:33+0000"
                },
                "children": {
                    "href": "https://api.agrofoto.pl/forums/178-jeczmien/children",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/forums/178-jeczmien",
                            "title": "Jęczmień",
                            "icon": "http://www.agrofoto.pl/forum/uploads/forumicons/41-icon-2145d8666c5e8ca7b66e6f57d61b939b.jpg",
                            "unread": true,
                            "topic_count": 107,
                            "posts_count": 4472,
                            "latest_topic": {
                                "href": "https://api.agrofoto.pl/topics/54612-jeczmien-hybrydowy",
                                "title": "jęczmień hybrydowy",
                                "user": {
                                    "href": "https://api.agrofoto.pl/users/69429-rapscase",
                                    "name": "RAPSCASE",
                                    "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-14237.jpg"
                                },
                                "updated_time": "2011-09-02T16:12:33+0000"
                            }
                        }
                    ],
                    "next": {
                        "href": "https://api.agrofoto.pl/forums/178-jeczmien/children?page=1&limit=25"
                    },
                    "previous": null
                },
                "parent": {
                    "href": "https://api.agrofoto.pl/forums/41-zboza",
                    "title": "Zboża",
                    "parent": {
                        "href": "https://api.agrofoto.pl/forums/19-produkcja-roslinna",
                        "title": "Produkcja roślinna",
                        "parent": {
                            "href": "https://api.agrofoto.pl/forums/0",
                            "title": "Forum"
                        }
                    }
                },
                "hot": {
                    "href": "https://api.agrofoto.pl/forums/0/hot",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/topics/2868-mlody-rolnik-nowe-zasady",
                            "title": "MŁODY ROLNIK (nowe zasady)",
                            "posts_count": 13807,
                            "displayed_count": 1497404,
                            "latest_post": {
                                "href": "https://api.agrofoto.pl/topics/2868-mlody-rolnik-nowe-zasady/posts/13808",
                                "from": {
                                    "href": "https://api.agrofoto.pl/users/136140-kamilek1",
                                    "name": "Kamilek1",
                                    "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-136140.jpg"
                                },
                                "created_time": "2011-09-02T16:12:33+0000"
                            }
                        }
                    ],
                    "next": {
                        "href": "https://api.agrofoto.pl/forums/0/hot?page=1&limit=25"
                    }
                },
                "topics": {
                    "href": "https://api.agrofoto.pl/forums/178-jeczmien/topics",
                    "items": [
                        {
                            "href": "https://api.agrofoto.pl/topics/5005-jeczmien-ozimy-i-jary",
                            "title": "Jęczmień ozimy i jary",
                            "from": {
                                "href": "https://api.agrofoto.pl/users/837-miki7211",
                                "name": "Miki7211"
                            },
                            "created_time": "2011-09-02T16:12:33+0000",
                            "posts_count": 3068,
                            "displayed_count": 371883,
                            "latest_post": {
                                "href": "https://api.agrofoto.pl/topics/5005-jeczmien-ozimy-i-jary/posts/3069",
                                "from": {
                                    "href": "https://api.agrofoto.pl/users/8527-milanreal1",
                                    "name": "milanreal1",
                                    "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-8527.jpg"
                                },
                                "created_time": "2011-09-02T16:12:33+0000"
                            },
                            "pinned": true,
                            "hot": true
                        }
                    ],
                    "next": {
                        "href": "https://api.agrofoto.pl/forums/178-jeczmien/topics?page=1&limit=25"
                    },
                    "previous": null
                },
                "subscribe": {
                    "href": "https://api.agrofoto.pl/forums/178-jeczmien/subscribe",
                    "count": 3,
                    "subscribed": true
                }
            }

## Subscribe Forum [/forums/{id}/subscribe]

+ Parameters
    + id (string)

+ Model
    + Body
    
            {
                "href": "https://api.agrofoto.pl/forums/178-jeczmien/subscribe",
                "count": 3,
                "subscribed": true
            }

### Subscribe Forum [PUT]
+ Response 200 (application/json)

    [Subscribe Forum][]

### Unsubscribe Forum [DELETE]
+ Response 200

    [Subscribe Forum][]
    
## Forum children [/forums/{id}/children]
Subforums of given forum node.

### List forum children [GET]
+ Response 200 (application/json)
    + Body

            {
                "href": "https://api.agrofoto.pl/forums/178-jeczmien/children",
                "items": [
                    {
                        "href": "https://api.agrofoto.pl/forums/178-jeczmien",
                        "title": "Jęczmień",
                        "icon": "http://www.agrofoto.pl/forum/uploads/forumicons/41-icon-2145d8666c5e8ca7b66e6f57d61b939b.jpg",
                        "unread": true,
                        "topic_count": 107,
                        "posts_count": 4472,
                        "latest_topic": {
                            "href": "https://api.agrofoto.pl/topics/54612-jeczmien-hybrydowy",
                            "title": "jęczmień hybrydowy",
                            "user": {
                                "href": "https://api.agrofoto.pl/users/69429-rapscase",
                                "name": "RAPSCASE",
                                "thumb": "http://www.agrofoto.pl/forum/uploads/profile/photo-thumb-14237.jpg"
                            },
                            "updated_time": "2011-09-02T16:12:33+0000"
                        }
                    }
                ],
                "next": {
                    "href": "https://api.agrofoto.pl/forums/178-jeczmien/children?page=1&limit=25"
                },
                "previous": null
            }
